apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pythonapi
  name: pythonapi
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pythonapi
  type: NodePort
status:
  loadBalancer: {}
