apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: phpconsumer
  name: phpconsumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpconsumer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpconsumer
    spec:
      containers:
      - image: joelongtoe/phpconsumer
        name: phpconsumer
        resources: {}
status: {}
